site_name: Alex MacIntosh, PhD | AI Consultant & Scientist
site_description: Bridging the "Trust Gap" between technical execution and scientific integrity.
site_url: https://groundedscientific.ai

nav:
  - Home: index.md
  - About: about.md
  - Case Studies:
    - Overview: portfolio/index.md
    - Projects:
      - portfolio/projects/project-1.md
      - portfolio/projects/project-2.md
      - portfolio/projects/project-3.md
  - Blog:
    - blog/index.md 

theme:
  name: material
  features:
    - search.suggest
    - toc.integrate
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - content.tooltips
    - content.tabs.link
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: custom
      accent: custom  
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: custom
      accent: custom
  logo: assets/logo.png
  font:
    text: Inter
    code: Roboto Mono
  icon:
    # logo: material/slash-forward-box
  favicon: assets/logo.png

extra:
  generator: true
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:amacintosh@groundedscientific.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexmacintosh/
    - icon: fontawesome/brands/github
      link: https://github.com/armacintosh
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.com/citations?user=tm-2hnMAAAAJ&hl=en
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0002-5094-3774
  analytics:
    # provider: google
    # property: G-W9Y130NXVZ

extra_css:
  - stylesheets/extra.css
  - stylesheets/hero.css
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#111111"
  - blog:
      blog_dir: blog
      authors_file: "{blog}/.authors.yml"
      categories: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.keys

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js


copyright: |
  &copy; 2026 <a href="https://www.linkedin.com/in/alexmacintosh/" target="_blank" rel="noopener">Alex MacIntosh</a>. All rights reserved.